---

- name: Add repo
  action: apt_repository repo='ppa:ondrej/php'
  sudo: yes
  register: addingOndrejPHPRepo


- name: Update APT package cache
  action: apt update_cache=yes
  sudo: yes
  when: addingOndrejPHPRepo.changed

- name: Install PHP stuff
  apt: pkg="{{ item }}" state=latest update_cache=true
  sudo: yes
  with_items:
    - mysql-client
    - php7.0-fpm
    - php7.0-mysql
    - php7.0-mcrypt
    - php7.0-intl
    - php7.0-curl
    - php-apc
    - php-memcached
    - php7.0-gd
    - php-imagick
    - php7.0-mbstring
    - php7.0-xml
    - php-zip
    - php-redis
- name: Activates php mods
  command: phpenmod mcrypt
  sudo: yes

- lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf regexp='^;listen.owner =' line='listen.owner = www-data'"
  sudo: yes
- lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf regexp='^;listen.group =' line='listen.group = www-data'"
  sudo: yes
- lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf regexp='^;listen.mode =' line='listen.mode = 0666'"
  sudo: yes

- lineinfile: "dest={{ item }} state=present regexp='^upload_max_filesize' line='upload_max_filesize = {{ parameters.php.maxfilesize }}'"
  sudo: yes
  with_items:
    - /etc/php/7.0/fpm/php.ini
    - /etc/php/7.0/cli/php.ini

- lineinfile: "dest={{ item }} state=present regexp='^post_max_size' line='post_max_size = {{ parameters.php.maxfilesize }}'"
  sudo: yes
  with_items:
    - /etc/php/7.0/fpm/php.ini
    - /etc/php/7.0/cli/php.ini

- lineinfile: "dest={{ item }} state=present regexp='^session.save_handler' line='session.save_handler = memcached'"
  sudo: yes
  with_items:
    - /etc/php/7.0/fpm/php.ini
    - /etc/php/7.0/cli/php.ini

- lineinfile: dest={{ item }} backrefs=yes regexp='^;session.save_path' line='session.save_path = "{{ parameters.memcached.ip }}:{{ parameters.memcached.port }}"'
  sudo: yes
  with_items:
    - /etc/php/7.0/fpm/php.ini
    - /etc/php/7.0/cli/php.ini

- lineinfile: dest={{ item }} backrefs=yes regexp='^;date.timezone' line='date.timezone = "{{ parameters.timezone }}"'
  sudo: yes
  with_items:
    - /etc/php/7.0/fpm/php.ini
    - /etc/php/7.0/cli/php.ini

- name: Restart php7-fpm
  service: name=php7.0-fpm state=restarted
  sudo: yes
