---

- name: Install selenium related packages
  action: apt name="{{ item }}" state=latest update_cache=true
  sudo: yes
  with_items:
    - openjdk-6-jre-headless
    - xfonts-100dpi
    - xfonts-75dpi
    - xfonts-scalable
    - xfonts-cyrillic
    - xserver-xorg-core
    - xvfb
    - zip

- name: download chromedriver
  get_url: url=http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip dest=/home/vagrant/chromedriver_linux64.zip mode=0440
  sudo: yes

- name: unzip chromedriver
  shell: "unzip /home/vagrant/chromedriver_linux64.zip"
  sudo: yes

- name: move chromedriver to /usr/local/bin
  shell: "sudo mv chromedriver /usr/local/bin"
  sudo: yes

- name: make chromdriver executable
  shell: "chmod +x /usr/local/bin/chromedriver"
  sudo: yes

- name: Download firefox
  get_url: url=https://sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_43.0.4-0ubuntu1_amd64.deb/download dest=/home/vagrant/43.0.4.deb mode=0440
  sudo: yes

- name: Install firefox
  shell: "dpkg -i /home/vagrant/43.0.4.deb"
  sudo: yes

- name: Add screen to crontab on restart
  cron: name="setup selenium screen on restart" special_time=reboot job="sh -c 'Xvfb :99 -ac -screen 0 1024x768x8 > /tmp/xvfb.log 2>&1 &'"
  sudo: yes
- name: Create selenium folder
  action: file path={{ parameters.selenium.path }} state=directory mode=0777
  sudo: yes
- name: Create selenium log folder
  action: file path={{ parameters.selenium.log_path }} state=directory mode=0777
  sudo: yes
- name: Download selenium
  shell: wget {{ parameters.selenium.url}}
  sudo: yes
  args:
    chdir: "{{ parameters.selenium.path }}"
    creates: "{{parameters.selenium.path}}/{{parameters.selenium.filename}}"
- name: Install service
  template: src=selenium.j2 dest=/etc/init.d/selenium owner=root group=root mode=755
  sudo: yes

- name: Add selenium service as startup script
  shell: update-rc.d selenium defaults
  sudo: yes
